- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enabling nodeJs 18 version
    ansible.builtin.command: dnf module enable nodejs:18 -y
  - name: installing nodeJs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: adding user
    ansible.builtin.user:
      name: roboshop
  - name: preparing a directory
    ansible.builtin.file: 
      path: /app
      state: directory
  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp 
  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
  



