- name: Setup MySQL on target host
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: RoboShop@1

  tasks:
    - name: Disable default MySQL module
      ansible.builtin.command:
        cmd: dnf module disable mysql -y

    - name: Copy MySQL repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Enable and start MySQL service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started

    - name: Set MySQL root password
      ansible.builtin.command:
        cmd: mysql_secure_installation --set-root-pass {{ mysql_root_password }}

    - name: Verify MySQL root login
      ansible.builtin.shell:
        cmd: mysql -uroot -p{{ mysql_root_password }} -e "SELECT VERSION();"
      register: mysql_version

    - name: Show MySQL version
      ansible.builtin.debug:
        var: mysql_version.stdout