- name: install shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
    mysql_host: mysql.opsora.space

  tasks:
    - name: Install Maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Remove existing app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp/shipping.zip

    - name: Extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: Copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: Check if cities schema exists
      ansible.builtin.command: >
        mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} -sN
        -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
      register: schema

    - name: Print schema check result
      ansible.builtin.debug:
        msg: "schema output: {{ schema.stdout }}"

    - name: Check if shipping.sql exists
      ansible.builtin.stat:
        path: /app/schema/shipping.sql
      register: shipping_sql

    - name: Download shipping.sql if missing
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/viho-kernel/roboshop-ansible/main/shipping/schema/shipping.sql
        dest: /app/schema/shipping.sql
      when: not shipping_sql.stat.exists

    - name: Load cities data
      ansible.builtin.shell: >
        mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }}
        < /app/schema/shipping.sql
      when: schema.stdout != "1"

    - name: Start and enable shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes